---
# tasks file for firstrole
- name: install apache2
  ansible.builtin.apt:
   name: apache2
   state: present
   update_cache: yes
  notify:
    - start apache2
- name: copy .html from here to server /var/www
  copy:
    src: files/index.html
    dest: /var/www/html
 
